version: "3"

services:
  # Container that runs HDFS NameNode and DataNode services
  hdfs-namenode:
    image: hdfs-namenode
    hostname: hdfs-namenode-host
    ports:
      # HDFS port
      - "9000:9000"
      # HDFS NameNode WebUI
      - "50070:50070"
    # Adjust according to the resources available on host machine
#    cpu_shares: 3000
#    mem_limit: 2g

  # Container that runs HDFS DataNode service
  hdfs-datanode:
    image: hdfs-datanode
    hostname: hdfs-datanode-host
    links:
      - hdfs-namenode
    environment:
      # NAMENODE_HOSTNAME is the hostname of the container running Namenode service
      - NAMENODE_HOSTNAME=hdfs-namenode-host
    # Adjust according to the resources available on host machine
#    cpu_shares: 3000
#    mem_limit: 2g

  # Container that runs Spark Master and Worker services
  spark-master:
    image: spark-master
    hostname: spark-master-host
    links:
      - hdfs-namenode
    ports:
      # Spark master WebUI port
      - "8080:8080"
      # Spark master job submission port
      - "7077:7077"
    environment:
      # NAMENODE_HOSTNAME is the hostname of the container running Namenode service
      - NAMENODE_HOSTNAME=hdfs-namenode-host
    # Adjust according to the resources available on host machine
#    cpu_shares: 3000
#    mem_limit: 2g

  # Container that runs Spark Worker service
  spark-slave:
    image: spark-slave
    hostname: spark-slave-host
    links:
      - hdfs-namenode
      - spark-master
    environment:
      # NAMENODE_HOSTNAME is the hostname of the container running Namenode service
      - NAMENODE_HOSTNAME=hdfs-namenode-host
      # MASTER_HOSTNAME is the hostname of the container running Spark master service
      - MASTER_HOSTNAME=spark-master-host
    # Adjust according to the resources available on host machine
#    cpu_shares: 3000
#    mem_limit: 2g

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ZOOKEEPER_CLIENT_PORT= 2181
      - ZOOKEEPER_TICK_TIME= 2000

  broker:
    image: confluentinc/cp-kafka:latest
    hostname: broker
    depends_on:
      - zookeeper
    ports:
      - '19092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_IN://broker:9092, LISTENER_OUT://localhost:19092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_IN:PLAINTEXT,LISTENER_OUT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_IN
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1

  neo4j:
    image: neo4j:latest       ## image: neo4j:3.5.2         ## we use neo4j v3
    ports:                    ## publish ports to have Web UI
      - "17474:7474"
      - "17687:7687" # Bolt
    volumes:                  ## adds folder with login/password
      - ./db/dbms:/data/dbms2
    environment:
      - NEO4J_HEAP_MEMORY=2048
      - NEO4J_CACHE_MEMORY=1G
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_dbms_mode=CORE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes 
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687